import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import "./Rating.css";
import Script from "next/script";
import { GoogleAnalytics } from "@next/third-parties/google";
import { cookies } from "next/headers";
import { DEFAULT_THEME } from "./consts";

// const inter = Inter({ subsets: ["latin"] });
const inter = { className: "font" };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get("theme")?.value ?? DEFAULT_THEME;
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Azeret+Mono:wght@100..900&display=swap"
          rel="stylesheet"
        />
        <GoogleAnalytics gaId="G-DSDJG1LG9W" />
        <Script id="segment">
          {`!function(){var i="analytics",analytics=window[i]=window[i]||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","screen","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware","register"];analytics.factory=function(e){return function(){if(window[i].initialized)return window[i][e].apply(window[i],arguments);var n=Array.prototype.slice.call(arguments);if(["track","screen","alias","group","page","identify"].indexOf(e)>-1){var c=document.querySelector("link[rel='canonical']");n.push({__t:"bpc",c:c&&c.getAttribute("href")||void 0,p:location.pathname,u:location.href,s:location.search,t:document.title,r:document.referrer})}n.unshift(e);analytics.push(n);return analytics}};for(var n=0;n<analytics.methods.length;n++){var key=analytics.methods[n];analytics[key]=analytics.factory(key)}analytics.load=function(key,n){var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.setAttribute("data-global-segment-analytics-key",i);t.src="https://cdn.segment.com/analytics.js/v1/" + key + "/analytics.min.js";var r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(t,r);analytics._loadOptions=n};analytics._writeKey="hxJSE9N5EKSvRXnfP39jLX7TE6IgVpl9";;analytics.SNIPPET_VERSION="5.2.0";
  analytics.load("hxJSE9N5EKSvRXnfP39jLX7TE6IgVpl9");
  analytics.page();
  }}();`}
        </Script>
      </head>
      <body className={`${inter.className} theme theme-${theme}`}>
        {children}
      </body>
    </html>
  );
}
